// Graywolf modem ↔ application IPC protocol.
//
// Wire format: length-prefixed IpcMessage frames over a Unix domain socket.
// Each frame is [4 bytes big-endian length][IpcMessage protobuf bytes].
//
// All messages are wrapped in the IpcMessage oneof envelope so that a single
// bidirectional stream can carry both directions without a separate type tag.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/graywolf.proto

package ipcproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IpcMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*IpcMessage_ReceivedFrame
	//	*IpcMessage_DcdChange
	//	*IpcMessage_StatusUpdate
	//	*IpcMessage_ModemReady
	//	*IpcMessage_TransmitFrame
	//	*IpcMessage_ConfigureChannel
	//	*IpcMessage_ConfigureAudio
	//	*IpcMessage_ConfigurePtt
	//	*IpcMessage_StartAudio
	//	*IpcMessage_StopAudio
	//	*IpcMessage_Shutdown
	Payload       isIpcMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IpcMessage) Reset() {
	*x = IpcMessage{}
	mi := &file_proto_graywolf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IpcMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IpcMessage) ProtoMessage() {}

func (x *IpcMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graywolf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IpcMessage.ProtoReflect.Descriptor instead.
func (*IpcMessage) Descriptor() ([]byte, []int) {
	return file_proto_graywolf_proto_rawDescGZIP(), []int{0}
}

func (x *IpcMessage) GetPayload() isIpcMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *IpcMessage) GetReceivedFrame() *ReceivedFrame {
	if x != nil {
		if x, ok := x.Payload.(*IpcMessage_ReceivedFrame); ok {
			return x.ReceivedFrame
		}
	}
	return nil
}

func (x *IpcMessage) GetDcdChange() *DcdChange {
	if x != nil {
		if x, ok := x.Payload.(*IpcMessage_DcdChange); ok {
			return x.DcdChange
		}
	}
	return nil
}

func (x *IpcMessage) GetStatusUpdate() *StatusUpdate {
	if x != nil {
		if x, ok := x.Payload.(*IpcMessage_StatusUpdate); ok {
			return x.StatusUpdate
		}
	}
	return nil
}

func (x *IpcMessage) GetModemReady() *ModemReady {
	if x != nil {
		if x, ok := x.Payload.(*IpcMessage_ModemReady); ok {
			return x.ModemReady
		}
	}
	return nil
}

func (x *IpcMessage) GetTransmitFrame() *TransmitFrame {
	if x != nil {
		if x, ok := x.Payload.(*IpcMessage_TransmitFrame); ok {
			return x.TransmitFrame
		}
	}
	return nil
}

func (x *IpcMessage) GetConfigureChannel() *ConfigureChannel {
	if x != nil {
		if x, ok := x.Payload.(*IpcMessage_ConfigureChannel); ok {
			return x.ConfigureChannel
		}
	}
	return nil
}

func (x *IpcMessage) GetConfigureAudio() *ConfigureAudio {
	if x != nil {
		if x, ok := x.Payload.(*IpcMessage_ConfigureAudio); ok {
			return x.ConfigureAudio
		}
	}
	return nil
}

func (x *IpcMessage) GetConfigurePtt() *ConfigurePtt {
	if x != nil {
		if x, ok := x.Payload.(*IpcMessage_ConfigurePtt); ok {
			return x.ConfigurePtt
		}
	}
	return nil
}

func (x *IpcMessage) GetStartAudio() *StartAudio {
	if x != nil {
		if x, ok := x.Payload.(*IpcMessage_StartAudio); ok {
			return x.StartAudio
		}
	}
	return nil
}

func (x *IpcMessage) GetStopAudio() *StopAudio {
	if x != nil {
		if x, ok := x.Payload.(*IpcMessage_StopAudio); ok {
			return x.StopAudio
		}
	}
	return nil
}

func (x *IpcMessage) GetShutdown() *Shutdown {
	if x != nil {
		if x, ok := x.Payload.(*IpcMessage_Shutdown); ok {
			return x.Shutdown
		}
	}
	return nil
}

type isIpcMessage_Payload interface {
	isIpcMessage_Payload()
}

type IpcMessage_ReceivedFrame struct {
	// Rust modem → Go application
	ReceivedFrame *ReceivedFrame `protobuf:"bytes,1,opt,name=received_frame,json=receivedFrame,proto3,oneof"`
}

type IpcMessage_DcdChange struct {
	DcdChange *DcdChange `protobuf:"bytes,2,opt,name=dcd_change,json=dcdChange,proto3,oneof"`
}

type IpcMessage_StatusUpdate struct {
	StatusUpdate *StatusUpdate `protobuf:"bytes,3,opt,name=status_update,json=statusUpdate,proto3,oneof"`
}

type IpcMessage_ModemReady struct {
	ModemReady *ModemReady `protobuf:"bytes,4,opt,name=modem_ready,json=modemReady,proto3,oneof"`
}

type IpcMessage_TransmitFrame struct {
	// Go application → Rust modem
	TransmitFrame *TransmitFrame `protobuf:"bytes,10,opt,name=transmit_frame,json=transmitFrame,proto3,oneof"`
}

type IpcMessage_ConfigureChannel struct {
	ConfigureChannel *ConfigureChannel `protobuf:"bytes,11,opt,name=configure_channel,json=configureChannel,proto3,oneof"`
}

type IpcMessage_ConfigureAudio struct {
	ConfigureAudio *ConfigureAudio `protobuf:"bytes,12,opt,name=configure_audio,json=configureAudio,proto3,oneof"`
}

type IpcMessage_ConfigurePtt struct {
	ConfigurePtt *ConfigurePtt `protobuf:"bytes,13,opt,name=configure_ptt,json=configurePtt,proto3,oneof"`
}

type IpcMessage_StartAudio struct {
	StartAudio *StartAudio `protobuf:"bytes,14,opt,name=start_audio,json=startAudio,proto3,oneof"`
}

type IpcMessage_StopAudio struct {
	StopAudio *StopAudio `protobuf:"bytes,15,opt,name=stop_audio,json=stopAudio,proto3,oneof"`
}

type IpcMessage_Shutdown struct {
	Shutdown *Shutdown `protobuf:"bytes,16,opt,name=shutdown,proto3,oneof"`
}

func (*IpcMessage_ReceivedFrame) isIpcMessage_Payload() {}

func (*IpcMessage_DcdChange) isIpcMessage_Payload() {}

func (*IpcMessage_StatusUpdate) isIpcMessage_Payload() {}

func (*IpcMessage_ModemReady) isIpcMessage_Payload() {}

func (*IpcMessage_TransmitFrame) isIpcMessage_Payload() {}

func (*IpcMessage_ConfigureChannel) isIpcMessage_Payload() {}

func (*IpcMessage_ConfigureAudio) isIpcMessage_Payload() {}

func (*IpcMessage_ConfigurePtt) isIpcMessage_Payload() {}

func (*IpcMessage_StartAudio) isIpcMessage_Payload() {}

func (*IpcMessage_StopAudio) isIpcMessage_Payload() {}

func (*IpcMessage_Shutdown) isIpcMessage_Payload() {}

// A successfully decoded AX.25 frame with demodulator metadata.
type ReceivedFrame struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Channel         uint32                 `protobuf:"varint,1,opt,name=channel,proto3" json:"channel,omitempty"`                                           // logical radio channel
	Subchan         uint32                 `protobuf:"varint,2,opt,name=subchan,proto3" json:"subchan,omitempty"`                                           // demodulator subchannel
	Slice           uint32                 `protobuf:"varint,3,opt,name=slice,proto3" json:"slice,omitempty"`                                               // slicer index
	Data            []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`                                                  // AX.25 frame bytes, FCS stripped
	Quality         int32                  `protobuf:"varint,5,opt,name=quality,proto3" json:"quality,omitempty"`                                           // 0..100 decoder quality
	AudioLevelMark  float32                `protobuf:"fixed32,6,opt,name=audio_level_mark,json=audioLevelMark,proto3" json:"audio_level_mark,omitempty"`    // mark level at time of capture
	AudioLevelSpace float32                `protobuf:"fixed32,7,opt,name=audio_level_space,json=audioLevelSpace,proto3" json:"audio_level_space,omitempty"` // space level at time of capture
	SpeedError      float32                `protobuf:"fixed32,8,opt,name=speed_error,json=speedError,proto3" json:"speed_error,omitempty"`                  // baud-rate error, percent
	Retry           string                 `protobuf:"bytes,9,opt,name=retry,proto3" json:"retry,omitempty"`                                                // "none" | "single" | "double"
	TimestampNs     uint64                 `protobuf:"varint,10,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`               // monotonic capture time
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReceivedFrame) Reset() {
	*x = ReceivedFrame{}
	mi := &file_proto_graywolf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceivedFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceivedFrame) ProtoMessage() {}

func (x *ReceivedFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graywolf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceivedFrame.ProtoReflect.Descriptor instead.
func (*ReceivedFrame) Descriptor() ([]byte, []int) {
	return file_proto_graywolf_proto_rawDescGZIP(), []int{1}
}

func (x *ReceivedFrame) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *ReceivedFrame) GetSubchan() uint32 {
	if x != nil {
		return x.Subchan
	}
	return 0
}

func (x *ReceivedFrame) GetSlice() uint32 {
	if x != nil {
		return x.Slice
	}
	return 0
}

func (x *ReceivedFrame) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ReceivedFrame) GetQuality() int32 {
	if x != nil {
		return x.Quality
	}
	return 0
}

func (x *ReceivedFrame) GetAudioLevelMark() float32 {
	if x != nil {
		return x.AudioLevelMark
	}
	return 0
}

func (x *ReceivedFrame) GetAudioLevelSpace() float32 {
	if x != nil {
		return x.AudioLevelSpace
	}
	return 0
}

func (x *ReceivedFrame) GetSpeedError() float32 {
	if x != nil {
		return x.SpeedError
	}
	return 0
}

func (x *ReceivedFrame) GetRetry() string {
	if x != nil {
		return x.Retry
	}
	return ""
}

func (x *ReceivedFrame) GetTimestampNs() uint64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

// Data Carrier Detect state transition.
type DcdChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       uint32                 `protobuf:"varint,1,opt,name=channel,proto3" json:"channel,omitempty"`
	Subchan       uint32                 `protobuf:"varint,2,opt,name=subchan,proto3" json:"subchan,omitempty"`
	Slice         uint32                 `protobuf:"varint,3,opt,name=slice,proto3" json:"slice,omitempty"`
	Detected      bool                   `protobuf:"varint,4,opt,name=detected,proto3" json:"detected,omitempty"`
	TimestampNs   uint64                 `protobuf:"varint,5,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DcdChange) Reset() {
	*x = DcdChange{}
	mi := &file_proto_graywolf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DcdChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DcdChange) ProtoMessage() {}

func (x *DcdChange) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graywolf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DcdChange.ProtoReflect.Descriptor instead.
func (*DcdChange) Descriptor() ([]byte, []int) {
	return file_proto_graywolf_proto_rawDescGZIP(), []int{2}
}

func (x *DcdChange) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *DcdChange) GetSubchan() uint32 {
	if x != nil {
		return x.Subchan
	}
	return 0
}

func (x *DcdChange) GetSlice() uint32 {
	if x != nil {
		return x.Slice
	}
	return 0
}

func (x *DcdChange) GetDetected() bool {
	if x != nil {
		return x.Detected
	}
	return false
}

func (x *DcdChange) GetTimestampNs() uint64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

// Periodic health / metrics update. Consumed by Go for Prometheus export.
type StatusUpdate struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Channel          uint32                 `protobuf:"varint,1,opt,name=channel,proto3" json:"channel,omitempty"`
	RxFrames         uint64                 `protobuf:"varint,2,opt,name=rx_frames,json=rxFrames,proto3" json:"rx_frames,omitempty"`
	RxBadFcs         uint64                 `protobuf:"varint,3,opt,name=rx_bad_fcs,json=rxBadFcs,proto3" json:"rx_bad_fcs,omitempty"`
	TxFrames         uint64                 `protobuf:"varint,4,opt,name=tx_frames,json=txFrames,proto3" json:"tx_frames,omitempty"`
	DcdTransitions   uint64                 `protobuf:"varint,5,opt,name=dcd_transitions,json=dcdTransitions,proto3" json:"dcd_transitions,omitempty"`
	AudioLevelMark   float32                `protobuf:"fixed32,6,opt,name=audio_level_mark,json=audioLevelMark,proto3" json:"audio_level_mark,omitempty"`
	AudioLevelSpace  float32                `protobuf:"fixed32,7,opt,name=audio_level_space,json=audioLevelSpace,proto3" json:"audio_level_space,omitempty"`
	AudioLevelPeak   float32                `protobuf:"fixed32,8,opt,name=audio_level_peak,json=audioLevelPeak,proto3" json:"audio_level_peak,omitempty"`
	DcdState         bool                   `protobuf:"varint,9,opt,name=dcd_state,json=dcdState,proto3" json:"dcd_state,omitempty"`
	ShutdownComplete bool                   `protobuf:"varint,10,opt,name=shutdown_complete,json=shutdownComplete,proto3" json:"shutdown_complete,omitempty"` // final status before process exit
	TimestampNs      uint64                 `protobuf:"varint,11,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StatusUpdate) Reset() {
	*x = StatusUpdate{}
	mi := &file_proto_graywolf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusUpdate) ProtoMessage() {}

func (x *StatusUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graywolf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusUpdate.ProtoReflect.Descriptor instead.
func (*StatusUpdate) Descriptor() ([]byte, []int) {
	return file_proto_graywolf_proto_rawDescGZIP(), []int{3}
}

func (x *StatusUpdate) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *StatusUpdate) GetRxFrames() uint64 {
	if x != nil {
		return x.RxFrames
	}
	return 0
}

func (x *StatusUpdate) GetRxBadFcs() uint64 {
	if x != nil {
		return x.RxBadFcs
	}
	return 0
}

func (x *StatusUpdate) GetTxFrames() uint64 {
	if x != nil {
		return x.TxFrames
	}
	return 0
}

func (x *StatusUpdate) GetDcdTransitions() uint64 {
	if x != nil {
		return x.DcdTransitions
	}
	return 0
}

func (x *StatusUpdate) GetAudioLevelMark() float32 {
	if x != nil {
		return x.AudioLevelMark
	}
	return 0
}

func (x *StatusUpdate) GetAudioLevelSpace() float32 {
	if x != nil {
		return x.AudioLevelSpace
	}
	return 0
}

func (x *StatusUpdate) GetAudioLevelPeak() float32 {
	if x != nil {
		return x.AudioLevelPeak
	}
	return 0
}

func (x *StatusUpdate) GetDcdState() bool {
	if x != nil {
		return x.DcdState
	}
	return false
}

func (x *StatusUpdate) GetShutdownComplete() bool {
	if x != nil {
		return x.ShutdownComplete
	}
	return false
}

func (x *StatusUpdate) GetTimestampNs() uint64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

// Sent once after the modem has bound its IPC socket, accepted a connection,
// and is ready to receive configuration messages.
type ModemReady struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Pid           uint64                 `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModemReady) Reset() {
	*x = ModemReady{}
	mi := &file_proto_graywolf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModemReady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModemReady) ProtoMessage() {}

func (x *ModemReady) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graywolf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModemReady.ProtoReflect.Descriptor instead.
func (*ModemReady) Descriptor() ([]byte, []int) {
	return file_proto_graywolf_proto_rawDescGZIP(), []int{4}
}

func (x *ModemReady) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ModemReady) GetPid() uint64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

// Request transmission of a raw AX.25 frame on a specific channel.
type TransmitFrame struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Channel           uint32                 `protobuf:"varint,1,opt,name=channel,proto3" json:"channel,omitempty"`
	Data              []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`                                                       // AX.25 frame bytes, no FCS (modem appends)
	TxdelayOverrideMs uint32                 `protobuf:"varint,3,opt,name=txdelay_override_ms,json=txdelayOverrideMs,proto3" json:"txdelay_override_ms,omitempty"` // 0 = use configured default
	TxtailOverrideMs  uint32                 `protobuf:"varint,4,opt,name=txtail_override_ms,json=txtailOverrideMs,proto3" json:"txtail_override_ms,omitempty"`
	Priority          uint32                 `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"` // higher = sooner
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TransmitFrame) Reset() {
	*x = TransmitFrame{}
	mi := &file_proto_graywolf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransmitFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransmitFrame) ProtoMessage() {}

func (x *TransmitFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graywolf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransmitFrame.ProtoReflect.Descriptor instead.
func (*TransmitFrame) Descriptor() ([]byte, []int) {
	return file_proto_graywolf_proto_rawDescGZIP(), []int{5}
}

func (x *TransmitFrame) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *TransmitFrame) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *TransmitFrame) GetTxdelayOverrideMs() uint32 {
	if x != nil {
		return x.TxdelayOverrideMs
	}
	return 0
}

func (x *TransmitFrame) GetTxtailOverrideMs() uint32 {
	if x != nil {
		return x.TxtailOverrideMs
	}
	return 0
}

func (x *TransmitFrame) GetPriority() uint32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

// Configure a logical radio channel's demodulator parameters.
type ConfigureChannel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       uint32                 `protobuf:"varint,1,opt,name=channel,proto3" json:"channel,omitempty"`
	DeviceId      uint32                 `protobuf:"varint,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`             // audio device this channel reads from
	AudioChannel  uint32                 `protobuf:"varint,3,opt,name=audio_channel,json=audioChannel,proto3" json:"audio_channel,omitempty"` // 0=left / mono, 1=right
	Baud          uint32                 `protobuf:"varint,4,opt,name=baud,proto3" json:"baud,omitempty"`                                     // 1200, 2400, 4800, 9600
	MarkFreq      uint32                 `protobuf:"varint,5,opt,name=mark_freq,json=markFreq,proto3" json:"mark_freq,omitempty"`
	SpaceFreq     uint32                 `protobuf:"varint,6,opt,name=space_freq,json=spaceFreq,proto3" json:"space_freq,omitempty"`
	ModemType     string                 `protobuf:"bytes,7,opt,name=modem_type,json=modemType,proto3" json:"modem_type,omitempty"` // "afsk" (phase 1), "psk", "9600" later
	Profile       string                 `protobuf:"bytes,8,opt,name=profile,proto3" json:"profile,omitempty"`                      // "A" | "B"
	NumSlicers    uint32                 `protobuf:"varint,9,opt,name=num_slicers,json=numSlicers,proto3" json:"num_slicers,omitempty"`
	FixBits       string                 `protobuf:"bytes,10,opt,name=fix_bits,json=fixBits,proto3" json:"fix_bits,omitempty"` // "none" | "single" | "double"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureChannel) Reset() {
	*x = ConfigureChannel{}
	mi := &file_proto_graywolf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureChannel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureChannel) ProtoMessage() {}

func (x *ConfigureChannel) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graywolf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureChannel.ProtoReflect.Descriptor instead.
func (*ConfigureChannel) Descriptor() ([]byte, []int) {
	return file_proto_graywolf_proto_rawDescGZIP(), []int{6}
}

func (x *ConfigureChannel) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *ConfigureChannel) GetDeviceId() uint32 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *ConfigureChannel) GetAudioChannel() uint32 {
	if x != nil {
		return x.AudioChannel
	}
	return 0
}

func (x *ConfigureChannel) GetBaud() uint32 {
	if x != nil {
		return x.Baud
	}
	return 0
}

func (x *ConfigureChannel) GetMarkFreq() uint32 {
	if x != nil {
		return x.MarkFreq
	}
	return 0
}

func (x *ConfigureChannel) GetSpaceFreq() uint32 {
	if x != nil {
		return x.SpaceFreq
	}
	return 0
}

func (x *ConfigureChannel) GetModemType() string {
	if x != nil {
		return x.ModemType
	}
	return ""
}

func (x *ConfigureChannel) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *ConfigureChannel) GetNumSlicers() uint32 {
	if x != nil {
		return x.NumSlicers
	}
	return 0
}

func (x *ConfigureChannel) GetFixBits() string {
	if x != nil {
		return x.FixBits
	}
	return ""
}

// Configure an audio source (soundcard, SDR UDP, stdin, FLAC file).
type ConfigureAudio struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      uint32                 `protobuf:"varint,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	DeviceName    string                 `protobuf:"bytes,2,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"` // cpal device name, "stdin", or file path
	SampleRate    uint32                 `protobuf:"varint,3,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`
	Channels      uint32                 `protobuf:"varint,4,opt,name=channels,proto3" json:"channels,omitempty"`                      // 1=mono, 2=stereo
	SourceType    string                 `protobuf:"bytes,5,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"` // "soundcard" | "stdin" | "flac" | "sdr_udp"
	Format        string                 `protobuf:"bytes,6,opt,name=format,proto3" json:"format,omitempty"`                           // "s16le" | "f32" etc. (source-specific)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureAudio) Reset() {
	*x = ConfigureAudio{}
	mi := &file_proto_graywolf_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureAudio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureAudio) ProtoMessage() {}

func (x *ConfigureAudio) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graywolf_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureAudio.ProtoReflect.Descriptor instead.
func (*ConfigureAudio) Descriptor() ([]byte, []int) {
	return file_proto_graywolf_proto_rawDescGZIP(), []int{7}
}

func (x *ConfigureAudio) GetDeviceId() uint32 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *ConfigureAudio) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *ConfigureAudio) GetSampleRate() uint32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

func (x *ConfigureAudio) GetChannels() uint32 {
	if x != nil {
		return x.Channels
	}
	return 0
}

func (x *ConfigureAudio) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *ConfigureAudio) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

// Configure PTT (push-to-talk) control for a channel.
type ConfigurePtt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       uint32                 `protobuf:"varint,1,opt,name=channel,proto3" json:"channel,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"` // "serial_rts" | "serial_dtr" | "gpio" | "cm108" | "none"
	Device        string                 `protobuf:"bytes,3,opt,name=device,proto3" json:"device,omitempty"`
	TxdelayMs     uint32                 `protobuf:"varint,4,opt,name=txdelay_ms,json=txdelayMs,proto3" json:"txdelay_ms,omitempty"`
	TxtailMs      uint32                 `protobuf:"varint,5,opt,name=txtail_ms,json=txtailMs,proto3" json:"txtail_ms,omitempty"`
	SlottimeMs    uint32                 `protobuf:"varint,6,opt,name=slottime_ms,json=slottimeMs,proto3" json:"slottime_ms,omitempty"`
	Persist       uint32                 `protobuf:"varint,7,opt,name=persist,proto3" json:"persist,omitempty"` // p-persistence 0..255
	DwaitMs       uint32                 `protobuf:"varint,8,opt,name=dwait_ms,json=dwaitMs,proto3" json:"dwait_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigurePtt) Reset() {
	*x = ConfigurePtt{}
	mi := &file_proto_graywolf_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigurePtt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurePtt) ProtoMessage() {}

func (x *ConfigurePtt) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graywolf_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigurePtt.ProtoReflect.Descriptor instead.
func (*ConfigurePtt) Descriptor() ([]byte, []int) {
	return file_proto_graywolf_proto_rawDescGZIP(), []int{8}
}

func (x *ConfigurePtt) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *ConfigurePtt) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *ConfigurePtt) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *ConfigurePtt) GetTxdelayMs() uint32 {
	if x != nil {
		return x.TxdelayMs
	}
	return 0
}

func (x *ConfigurePtt) GetTxtailMs() uint32 {
	if x != nil {
		return x.TxtailMs
	}
	return 0
}

func (x *ConfigurePtt) GetSlottimeMs() uint32 {
	if x != nil {
		return x.SlottimeMs
	}
	return 0
}

func (x *ConfigurePtt) GetPersist() uint32 {
	if x != nil {
		return x.Persist
	}
	return 0
}

func (x *ConfigurePtt) GetDwaitMs() uint32 {
	if x != nil {
		return x.DwaitMs
	}
	return 0
}

// Begin audio processing on all configured devices.
type StartAudio struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartAudio) Reset() {
	*x = StartAudio{}
	mi := &file_proto_graywolf_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartAudio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartAudio) ProtoMessage() {}

func (x *StartAudio) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graywolf_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartAudio.ProtoReflect.Descriptor instead.
func (*StartAudio) Descriptor() ([]byte, []int) {
	return file_proto_graywolf_proto_rawDescGZIP(), []int{9}
}

// Stop audio processing (for device hot-swap). Safe to follow with a new
// ConfigureAudio + StartAudio sequence.
type StopAudio struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopAudio) Reset() {
	*x = StopAudio{}
	mi := &file_proto_graywolf_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopAudio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopAudio) ProtoMessage() {}

func (x *StopAudio) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graywolf_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopAudio.ProtoReflect.Descriptor instead.
func (*StopAudio) Descriptor() ([]byte, []int) {
	return file_proto_graywolf_proto_rawDescGZIP(), []int{10}
}

// Graceful shutdown: finish current TX, deassert PTT, drain queues, exit.
type Shutdown struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimeoutMs     uint32                 `protobuf:"varint,1,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"` // max time to wait for drain, 0 = use default
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Shutdown) Reset() {
	*x = Shutdown{}
	mi := &file_proto_graywolf_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shutdown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shutdown) ProtoMessage() {}

func (x *Shutdown) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graywolf_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shutdown.ProtoReflect.Descriptor instead.
func (*Shutdown) Descriptor() ([]byte, []int) {
	return file_proto_graywolf_proto_rawDescGZIP(), []int{11}
}

func (x *Shutdown) GetTimeoutMs() uint32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

var File_proto_graywolf_proto protoreflect.FileDescriptor

const file_proto_graywolf_proto_rawDesc = "" +
	"\n" +
	"\x14proto/graywolf.proto\x12\bgraywolf\"\xb9\x05\n" +
	"\n" +
	"IpcMessage\x12@\n" +
	"\x0ereceived_frame\x18\x01 \x01(\v2\x17.graywolf.ReceivedFrameH\x00R\rreceivedFrame\x124\n" +
	"\n" +
	"dcd_change\x18\x02 \x01(\v2\x13.graywolf.DcdChangeH\x00R\tdcdChange\x12=\n" +
	"\rstatus_update\x18\x03 \x01(\v2\x16.graywolf.StatusUpdateH\x00R\fstatusUpdate\x127\n" +
	"\vmodem_ready\x18\x04 \x01(\v2\x14.graywolf.ModemReadyH\x00R\n" +
	"modemReady\x12@\n" +
	"\x0etransmit_frame\x18\n" +
	" \x01(\v2\x17.graywolf.TransmitFrameH\x00R\rtransmitFrame\x12I\n" +
	"\x11configure_channel\x18\v \x01(\v2\x1a.graywolf.ConfigureChannelH\x00R\x10configureChannel\x12C\n" +
	"\x0fconfigure_audio\x18\f \x01(\v2\x18.graywolf.ConfigureAudioH\x00R\x0econfigureAudio\x12=\n" +
	"\rconfigure_ptt\x18\r \x01(\v2\x16.graywolf.ConfigurePttH\x00R\fconfigurePtt\x127\n" +
	"\vstart_audio\x18\x0e \x01(\v2\x14.graywolf.StartAudioH\x00R\n" +
	"startAudio\x124\n" +
	"\n" +
	"stop_audio\x18\x0f \x01(\v2\x13.graywolf.StopAudioH\x00R\tstopAudio\x120\n" +
	"\bshutdown\x18\x10 \x01(\v2\x12.graywolf.ShutdownH\x00R\bshutdownB\t\n" +
	"\apayload\"\xb7\x02\n" +
	"\rReceivedFrame\x12\x18\n" +
	"\achannel\x18\x01 \x01(\rR\achannel\x12\x18\n" +
	"\asubchan\x18\x02 \x01(\rR\asubchan\x12\x14\n" +
	"\x05slice\x18\x03 \x01(\rR\x05slice\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12\x18\n" +
	"\aquality\x18\x05 \x01(\x05R\aquality\x12(\n" +
	"\x10audio_level_mark\x18\x06 \x01(\x02R\x0eaudioLevelMark\x12*\n" +
	"\x11audio_level_space\x18\a \x01(\x02R\x0faudioLevelSpace\x12\x1f\n" +
	"\vspeed_error\x18\b \x01(\x02R\n" +
	"speedError\x12\x14\n" +
	"\x05retry\x18\t \x01(\tR\x05retry\x12!\n" +
	"\ftimestamp_ns\x18\n" +
	" \x01(\x04R\vtimestampNs\"\x94\x01\n" +
	"\tDcdChange\x12\x18\n" +
	"\achannel\x18\x01 \x01(\rR\achannel\x12\x18\n" +
	"\asubchan\x18\x02 \x01(\rR\asubchan\x12\x14\n" +
	"\x05slice\x18\x03 \x01(\rR\x05slice\x12\x1a\n" +
	"\bdetected\x18\x04 \x01(\bR\bdetected\x12!\n" +
	"\ftimestamp_ns\x18\x05 \x01(\x04R\vtimestampNs\"\x96\x03\n" +
	"\fStatusUpdate\x12\x18\n" +
	"\achannel\x18\x01 \x01(\rR\achannel\x12\x1b\n" +
	"\trx_frames\x18\x02 \x01(\x04R\brxFrames\x12\x1c\n" +
	"\n" +
	"rx_bad_fcs\x18\x03 \x01(\x04R\brxBadFcs\x12\x1b\n" +
	"\ttx_frames\x18\x04 \x01(\x04R\btxFrames\x12'\n" +
	"\x0fdcd_transitions\x18\x05 \x01(\x04R\x0edcdTransitions\x12(\n" +
	"\x10audio_level_mark\x18\x06 \x01(\x02R\x0eaudioLevelMark\x12*\n" +
	"\x11audio_level_space\x18\a \x01(\x02R\x0faudioLevelSpace\x12(\n" +
	"\x10audio_level_peak\x18\b \x01(\x02R\x0eaudioLevelPeak\x12\x1b\n" +
	"\tdcd_state\x18\t \x01(\bR\bdcdState\x12+\n" +
	"\x11shutdown_complete\x18\n" +
	" \x01(\bR\x10shutdownComplete\x12!\n" +
	"\ftimestamp_ns\x18\v \x01(\x04R\vtimestampNs\"8\n" +
	"\n" +
	"ModemReady\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\x04R\x03pid\"\xb7\x01\n" +
	"\rTransmitFrame\x12\x18\n" +
	"\achannel\x18\x01 \x01(\rR\achannel\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12.\n" +
	"\x13txdelay_override_ms\x18\x03 \x01(\rR\x11txdelayOverrideMs\x12,\n" +
	"\x12txtail_override_ms\x18\x04 \x01(\rR\x10txtailOverrideMs\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\rR\bpriority\"\xb3\x02\n" +
	"\x10ConfigureChannel\x12\x18\n" +
	"\achannel\x18\x01 \x01(\rR\achannel\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\rR\bdeviceId\x12#\n" +
	"\raudio_channel\x18\x03 \x01(\rR\faudioChannel\x12\x12\n" +
	"\x04baud\x18\x04 \x01(\rR\x04baud\x12\x1b\n" +
	"\tmark_freq\x18\x05 \x01(\rR\bmarkFreq\x12\x1d\n" +
	"\n" +
	"space_freq\x18\x06 \x01(\rR\tspaceFreq\x12\x1d\n" +
	"\n" +
	"modem_type\x18\a \x01(\tR\tmodemType\x12\x18\n" +
	"\aprofile\x18\b \x01(\tR\aprofile\x12\x1f\n" +
	"\vnum_slicers\x18\t \x01(\rR\n" +
	"numSlicers\x12\x19\n" +
	"\bfix_bits\x18\n" +
	" \x01(\tR\afixBits\"\xc4\x01\n" +
	"\x0eConfigureAudio\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\rR\bdeviceId\x12\x1f\n" +
	"\vdevice_name\x18\x02 \x01(\tR\n" +
	"deviceName\x12\x1f\n" +
	"\vsample_rate\x18\x03 \x01(\rR\n" +
	"sampleRate\x12\x1a\n" +
	"\bchannels\x18\x04 \x01(\rR\bchannels\x12\x1f\n" +
	"\vsource_type\x18\x05 \x01(\tR\n" +
	"sourceType\x12\x16\n" +
	"\x06format\x18\x06 \x01(\tR\x06format\"\xea\x01\n" +
	"\fConfigurePtt\x12\x18\n" +
	"\achannel\x18\x01 \x01(\rR\achannel\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x16\n" +
	"\x06device\x18\x03 \x01(\tR\x06device\x12\x1d\n" +
	"\n" +
	"txdelay_ms\x18\x04 \x01(\rR\ttxdelayMs\x12\x1b\n" +
	"\ttxtail_ms\x18\x05 \x01(\rR\btxtailMs\x12\x1f\n" +
	"\vslottime_ms\x18\x06 \x01(\rR\n" +
	"slottimeMs\x12\x18\n" +
	"\apersist\x18\a \x01(\rR\apersist\x12\x19\n" +
	"\bdwait_ms\x18\b \x01(\rR\adwaitMs\"\f\n" +
	"\n" +
	"StartAudio\"\v\n" +
	"\tStopAudio\")\n" +
	"\bShutdown\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x01 \x01(\rR\ttimeoutMsB-Z+github.com/chrissnell/graywolf/pkg/ipcprotob\x06proto3"

var (
	file_proto_graywolf_proto_rawDescOnce sync.Once
	file_proto_graywolf_proto_rawDescData []byte
)

func file_proto_graywolf_proto_rawDescGZIP() []byte {
	file_proto_graywolf_proto_rawDescOnce.Do(func() {
		file_proto_graywolf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_graywolf_proto_rawDesc), len(file_proto_graywolf_proto_rawDesc)))
	})
	return file_proto_graywolf_proto_rawDescData
}

var file_proto_graywolf_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_graywolf_proto_goTypes = []any{
	(*IpcMessage)(nil),       // 0: graywolf.IpcMessage
	(*ReceivedFrame)(nil),    // 1: graywolf.ReceivedFrame
	(*DcdChange)(nil),        // 2: graywolf.DcdChange
	(*StatusUpdate)(nil),     // 3: graywolf.StatusUpdate
	(*ModemReady)(nil),       // 4: graywolf.ModemReady
	(*TransmitFrame)(nil),    // 5: graywolf.TransmitFrame
	(*ConfigureChannel)(nil), // 6: graywolf.ConfigureChannel
	(*ConfigureAudio)(nil),   // 7: graywolf.ConfigureAudio
	(*ConfigurePtt)(nil),     // 8: graywolf.ConfigurePtt
	(*StartAudio)(nil),       // 9: graywolf.StartAudio
	(*StopAudio)(nil),        // 10: graywolf.StopAudio
	(*Shutdown)(nil),         // 11: graywolf.Shutdown
}
var file_proto_graywolf_proto_depIdxs = []int32{
	1,  // 0: graywolf.IpcMessage.received_frame:type_name -> graywolf.ReceivedFrame
	2,  // 1: graywolf.IpcMessage.dcd_change:type_name -> graywolf.DcdChange
	3,  // 2: graywolf.IpcMessage.status_update:type_name -> graywolf.StatusUpdate
	4,  // 3: graywolf.IpcMessage.modem_ready:type_name -> graywolf.ModemReady
	5,  // 4: graywolf.IpcMessage.transmit_frame:type_name -> graywolf.TransmitFrame
	6,  // 5: graywolf.IpcMessage.configure_channel:type_name -> graywolf.ConfigureChannel
	7,  // 6: graywolf.IpcMessage.configure_audio:type_name -> graywolf.ConfigureAudio
	8,  // 7: graywolf.IpcMessage.configure_ptt:type_name -> graywolf.ConfigurePtt
	9,  // 8: graywolf.IpcMessage.start_audio:type_name -> graywolf.StartAudio
	10, // 9: graywolf.IpcMessage.stop_audio:type_name -> graywolf.StopAudio
	11, // 10: graywolf.IpcMessage.shutdown:type_name -> graywolf.Shutdown
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_graywolf_proto_init() }
func file_proto_graywolf_proto_init() {
	if File_proto_graywolf_proto != nil {
		return
	}
	file_proto_graywolf_proto_msgTypes[0].OneofWrappers = []any{
		(*IpcMessage_ReceivedFrame)(nil),
		(*IpcMessage_DcdChange)(nil),
		(*IpcMessage_StatusUpdate)(nil),
		(*IpcMessage_ModemReady)(nil),
		(*IpcMessage_TransmitFrame)(nil),
		(*IpcMessage_ConfigureChannel)(nil),
		(*IpcMessage_ConfigureAudio)(nil),
		(*IpcMessage_ConfigurePtt)(nil),
		(*IpcMessage_StartAudio)(nil),
		(*IpcMessage_StopAudio)(nil),
		(*IpcMessage_Shutdown)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_graywolf_proto_rawDesc), len(file_proto_graywolf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_graywolf_proto_goTypes,
		DependencyIndexes: file_proto_graywolf_proto_depIdxs,
		MessageInfos:      file_proto_graywolf_proto_msgTypes,
	}.Build()
	File_proto_graywolf_proto = out.File
	file_proto_graywolf_proto_goTypes = nil
	file_proto_graywolf_proto_depIdxs = nil
}
